apiVersion: v1
kind: Service
metadata:
  name: retail-service
  namespace: retail
spec:
  type: NodePort
  selector:
    app: retail-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007